version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ./bin/rails s -p 3000 -b '0.0.0.0'
    env_file: .env
    depends_on:
      - database
      - maildev

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - .:/app
    environment:
      POSTGRES_DB: tuxedo_development

  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "1025:25"
